/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MonitoringAlert {
        "message": string;
        "type": string;
    }
    interface MonitoringChart {
        "data": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLMonitoringAlertElement extends Components.MonitoringAlert, HTMLStencilElement {
    }
    var HTMLMonitoringAlertElement: {
        prototype: HTMLMonitoringAlertElement;
        new (): HTMLMonitoringAlertElement;
    };
    interface HTMLMonitoringChartElement extends Components.MonitoringChart, HTMLStencilElement {
    }
    var HTMLMonitoringChartElement: {
        prototype: HTMLMonitoringChartElement;
        new (): HTMLMonitoringChartElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "monitoring-alert": HTMLMonitoringAlertElement;
        "monitoring-chart": HTMLMonitoringChartElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface MonitoringAlert {
        "message"?: string;
        "type"?: string;
    }
    interface MonitoringChart {
        "data"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "monitoring-alert": MonitoringAlert;
        "monitoring-chart": MonitoringChart;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "monitoring-alert": LocalJSX.MonitoringAlert & JSXBase.HTMLAttributes<HTMLMonitoringAlertElement>;
            "monitoring-chart": LocalJSX.MonitoringChart & JSXBase.HTMLAttributes<HTMLMonitoringChartElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
